spring:
  application:
    name: Personal-Bookmark

  datasource:
    url: jdbc:mysql://localhost/Note_tags?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true